import NavBar from "../components/NavBar";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import ClientProvider from "./ClientProvider";
export const metadata = {
  title: "Video Meeting",
  description: "Generated by Next.js",
};
import "@stream-io/video-react-sdk/dist/css/styles.css";

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <ClientProvider>
            <NavBar />
            <main className="mx-auto max-w-5xl px-3 py-6">{children}</main>
          </ClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
