import NavBar from "@/components/NavBar";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <NavBar />
          <main className="mx-auto max-w-5xl px-3 py-6">{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
